#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("QuietPlease.Resource", IsApplication=true)]

namespace QuietPlease
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int chargeActionLabel = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int chargingRadioGroup = 2131034113;
			
			// aapt resource value: 0x7f050003
			public const int chargingRingRadioButton = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int chargingSilentRadioButton = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int chargingVibrateRadioButton = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int notChargingActionLabel = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int notChargingRadioGroup = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int notChargingRingRadioButton = 2131034121;
			
			// aapt resource value: 0x7f05000b
			public const int notChargingSilentRadioButton = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int notChargingVibrateRadioButton = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int settingsLayout = 2131034112;
			
			// aapt resource value: 0x7f05000d
			public const int showNotificationsCheckBox = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int spacer1Label = 2131034118;
			
			// aapt resource value: 0x7f05000c
			public const int spacer2Label = 2131034124;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Settings = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int power_connected_action_text = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int power_connected_notification = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int power_disconnected_action_text = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int power_disconnected_notification = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int ring = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int silent = 2130968580;
			
			// aapt resource value: 0x7f040008
			public const int state_change_notifications_text = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int vibrate = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
